# -*- coding: utf-8 -*-
"""CatBoost & AdaBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLaY_gtWN0dd3_CCGRxN3CtbRyQjJ1sI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, AdaBoostClassifier
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/loan_approval_dataset.csv")

df.head()

df.isnull().sum()

df.shape

df.describe()

df.columns = df.columns.str.strip()
df['loan_status'] = df['loan_status'].str.strip().map({'Approved': '1', 'Rejected': '2'})

df

df.columns = df.columns.str.strip()
X = df.drop(['loan_status'], axis=1)
y = df['loan_status']

label_encoders = {}

categorical_cols = X.select_dtypes(include=['object']).columns

for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

random_forest_model = RandomForestRegressor(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)

accuracy_score = random_forest_model.score(X_test, y_test)
print("Accuracy Score:", accuracy_score)

lgm = lgb.LGBMRegressor(n_estimators=100, random_state=42)
lgm.fit(X_train, y_train.astype(int))

lgbm_model = lgb.LGBMRegressor(n_estimators=100, random_state=42)
lgbm_model.fit(X_train, y_train.astype(int))

lgbm_model = lgb.LGBMRegressor(n_estimators=100, random_state=42)
lgbm_model.fit(X_train, y_train.astype(int))
y_pred = lgbm_model.predict(X_test)
print("Predictions made with LightGBM.")

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.2f}")

accuracy_score = lgbm_model.score(X_test, y_test)
print("Accuracy Score:", accuracy_score)



# CATBOOSTCLASSIFIER

from sklearn.metrics import accuracy_score
model = CatBoostClassifier(iterations = 400 ,learning_rate=0.1,depth=6,loss_function='MultiClass',eval_metric='Accuracy',verbose=False,random_seed=42)
model.fit(X_train, y_train,)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))



#AdaBoostClassifier

from sklearn.metrics import accuracy_score
model = AdaBoostClassifier(n_estimators = 400 ,learning_rate=0.1,random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

