# -*- coding: utf-8 -*-
"""DecisionTree & Cart&Id3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiOY39RrJiriXC6o3KII2vsjRDr15W4t
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/breast-cancer.csv")

df.head()

df.isnull().sum()

df.info()

df['diagnosis'] = df['diagnosis'].map({'M': '1', 'B': '2'})

df.head()

X = df.drop(['diagnosis', 'id'], axis=1)

X = X.apply(pd.to_numeric, errors='coerce')
X.fillna(X.mean(), inplace=True)
y = df['diagnosis']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

cart = DecisionTreeClassifier(criterion="gini",random_state=42)

cart.fit(X_train, y_train)

cart_pred = cart.predict(X_test)

print("Accuracy:", accuracy_score(y_test, cart_pred))
print(confusion_matrix(y_test, cart_pred))
print(classification_report(y_test, cart_pred))

plt.figure(figsize=(18,10))

plot_tree(cart,feature_names=X.columns,class_names=y.unique().tolist(),filled=True,rounded=True)

plt.show()

id3 = DecisionTreeClassifier(criterion="entropy",random_state=42)

id3.fit(X_train, y_train)

id3_pred = id3.predict(X_test)

print("Accuracy:", accuracy_score(y_test, id3_pred))
print(confusion_matrix(y_test, id3_pred))
print(classification_report(y_test, id3_pred))

plt.figure(figsize=(18,10))

plot_tree(id3,feature_names=X.columns,class_names=y.unique().tolist(),filled=True,rounded=True)

plt.show()

!pip install chefboost
from chefboost import Chefboost as chef

chef_df = X.copy()

chef_df["Decision"] = y.map({'1': "Malignant", '2': "Benign"})

config = {"algorithm": "C4.5"}

model = chef.fit(chef_df, config=config)

sample_series = X.iloc[0]
sample = [float(x) for x in sample_series]

prediction = chef.predict(model, sample)

print("Prediction:", prediction)

importance = pd.DataFrame({"Feature": X.columns,"Importance": cart.feature_importances_})

importance = importance.sort_values(by="Importance",ascending=False)

print(importance)

results = pd.DataFrame({"Algorithm": ["CART", "ID3"],"Accuracy": [accuracy_score(y_test, cart_pred),accuracy_score(y_test, id3_pred)]})

print(results)