# -*- coding: utf-8 -*-
"""Extra_tree & Isolation_Forest .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NltdHs2NdjWN4vj6iSXrroSU6Dpb93TL
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import ExtraTreesClassifier,IsolationForest
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import sys
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/winequality-red.csv")

df

df.isnull().sum()

X = df.drop(['quality'], axis=1)
y = df['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = ExtraTreesClassifier(n_estimators=200,
max_features='sqrt',
min_samples_leaf=2,
random_state=42)

clf.fit(X_train, y_train)

y_pred_test = clf.predict(X_test)
y_pred_train = clf.predict(X_train)

print("Accuracy:", accuracy_score(y_test, y_pred_test))
print("Accuracy:", accuracy_score(y_train, y_pred_train))

model = IsolationForest(n_estimators=100,contamination=0.05,random_state=42)

model.fit(X)

predictions = model.predict(X)

scores = model.decision_function(X)

df = pd.DataFrame(X, columns=["Feature1", "Feature2"])
df["Prediction"] = predictions
df["Anomaly_Score"] = scores

print("Accuracy:", accuracy_score(y_test, y_pred_test))
print("Accuracy:", accuracy_score(y_train, y_pred_train))





model = CatBoostClassifier(learning_rate=0.1,depth=6,loss_function='MultiClass',eval_metric='Accuracy',verbose=False,random_seed=42)
model.fit(X_train, y_train,)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

