# -*- coding: utf-8 -*-
"""Lasso_Ridge_Elastic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YE6Vvd65SFwHvfFwIem_HS0WWmXD6K3q
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('/content/mtcars.csv')

df.head()

df.describe()

df.nunique()

df.isnull().sum()

x = df.drop(['mpg', 'model'], axis=1)
y = df['mpg']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

model = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model.fit(x_train, y_train)

model.score(x_train,y_train)

model.score(x_test,y_test)

"""LASSO MODEL"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso
lasso = Lasso(alpha=50, max_iter=100,tol=0.1)
lasso.fit(x_train, y_train)

df = pd.get_dummies(df ,drop_first=True)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

lasso.score(x_test,y_test)

lasso.score(x_train,y_train)

"""RIDGE MODEL"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
Ridge = Ridge(alpha=50, max_iter=100,tol=0.1)
Ridge.fit(x_train, y_train)

Ridge.score(x_test,y_test)

Ridge.score(x_train,y_train)

"""ELASTIC NET"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, ElasticNet
elastic = ElasticNet(alpha=50, max_iter=100,tol=0.1)
elastic.fit(x_train, y_train)

elastic.score(x_test,y_test)

elastic.score(x_train, y_train)

