# -*- coding: utf-8 -*-
"""Lasso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJecpfqTqQH8Eudkzy5cMiYcdfMBY6q7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Sample - Superstore.csv', encoding='latin1')

df.head()

df.isnull().sum()

df.info()

plt.xlabel('Sales')
plt.ylabel('Profit')
plt.scatter(df['Sales'],df['Profit'],color='red',marker='*')

x.head()

df = df.drop(['Row ID','Order ID','Customer ID','Postal Code'],axis=1)

df.head()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df.head()

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

x = df.drop(['Profit'], axis=1)
y = df['Profit']

numeric_cols = x.select_dtypes(include=['number']).columns

x = df[numeric_cols]
y = profit

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

df = pd.get_dummies(df ,drop_first=True)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(x_train,y_train)

y_pred = reg.predict(x_test)

score = r2_score(y_test,y_pred)
score

from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

lasso = Lasso(alpha=0.1)
lasso.fit(x_train,y_train)

train_pred = lasso.predict(x_train)
test_pred = lasso.predict(x_test)

train_r2 = r2_score(y_train,train_pred)
test_r2 = r2_score(y_test,test_pred)

train_mse = mean_squared_error(y_train, train_pred)
test_mse = mean_squared_error(y_test, test_pred)

print("Training Accuracy (R2):", train_r2)

print("Testing Accuracy (R2):", test_r2)

print("Training mse:", train_mse)
print("Testing mse:", test_mse)

predicted_profit = lasso.predict([[261.96, 3000, 0.0]])[0]
print(predicted_profit)

