# -*- coding: utf-8 -*-
"""LDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiouSsbIQWzyWq_yKLJIup1ZGXB2zM-G
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()
X = iris.data
y = iris.target

df = pd.DataFrame(X, columns=iris.feature_names)
df["Species"] = y
print("--- Dataset-oda First 5 Rows ---")
print(df.head())
print("\n" + "=" * 50 + "\n")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lda = LinearDiscriminantAnalysis()
lda.fit(X_train_scaled, y_train)

y_pred = lda.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"LDA Model Accuracy: {accuracy * 100:.2f}%")
print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

X_lda = lda.transform(X_train_scaled)

plt.figure(figsize=(8, 6))
colors = ["red", "green", "blue"]
for color, i, target_name in zip(colors, [0, 1, 2], iris.target_names):
    plt.scatter(
        X_lda[y_train == i, 0],
        X_lda[y_train == i, 1],
        alpha=0.8,
        color=color,
        label=target_name,
    )

plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.title("LDA: 3 ")
plt.xlabel("LD1 (Linear Discriminant 1)")
plt.ylabel("LD2 (Linear Discriminant 2)")
plt.show()