# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cz8LX49uR6lMENa66V96kdJhQH9w6lbn
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/HR_comma_sep.csv")
df.head()

plt.figure(figsize=(10, 6))
sns.barplot(x='Department', y='left', data=df)
plt.title('Employee Retention by Department')
plt.xlabel('Department')
plt.ylabel('Retention Rate')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(x='salary', y='left', data=df, order=['low', 'medium', 'high'])
plt.title('Employee Retention by Salary Level')
plt.xlabel('Salary Level')
plt.ylabel('Retention Rate')
plt.tight_layout()
plt.show()

X_train, X_test, y_train, y_test = train_test_split(df[['salary']],df.left,train_size=0.8)

X_test

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train_encoded, y_train)

X_test

y_predicted = model.predict(X_test_encoded)

model.score(X_test_encoded, y_test)

y_predicted