# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192SqqgszxSrYX3Yev3BqApbmSqpkQpCI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/Student_Performance.csv")

df.head()

df.info()

df.isnull().sum()

df['gender'] = df['gender'].map({'male': 1, 'female': 2, 'other': 3})
df['school_type'] = df['school_type'].map({'public': 1, 'private': 2})
df['internet_access'] = df['internet_access'].map({'yes': 1, 'no': 0})
df['extra_activities'] = df['extra_activities'].map({'yes': 1, 'no': 0})
df['parent_education'] = df['parent_education'].map({'no formal': 0,'high school': 1,'diploma': 2,'graduate': 3,'post graduate': 4,'phd': 5})
df['travel_time'] = df['travel_time'].map({'<15 min': 0,'15-30 min': 1,'30-60 min': 2,'>60 min': 3})
df['study_method'] = df['study_method'].map({'notes': 0,'textbook': 1,'group study': 2,'mixed': 3,'coaching': 4})

df.head()

def calculate_grade(score):
    if score >= 70:
        return '1'
    elif score >= 40:
        return '2'
    else:
        return '3'

df['calculated_grade'] = df['overall_score'].apply(calculate_grade)

df.head()

df = df.drop("final_grade",axis =1)

X = df.drop(['student_id', 'overall_score', 'calculated_grade'], axis=1)
y = df['calculated_grade']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

model = SVC(kernel="linear")
model.fit(X_train, y_train)

X_test = X_test.fillna(0)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
colors = {'1': 'green','2': 'blue','3': 'red'}
grade_labels = {'1': 'Level A','2': 'Level B','3': 'Level C'}
for grade_numeric, color in colors.items():
    subset = df[df["calculated_grade"] == grade_numeric]
    plt.scatter(subset["math_score"], subset["overall_score"], color=color,label=grade_labels[grade_numeric],s=50)

import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
colors = {'1': 'green','2': 'blue','3': 'red'}
grade_labels = {'1': 'Level A','2': 'Level B','3': 'Level C'}
for grade_numeric, color in colors.items():
    subset = df[df["calculated_grade"] == grade_numeric]
    plt.scatter(subset["math_score"], subset["overall_score"], color=color,label=grade_labels[grade_numeric],s=50)

plt.title("Student Classification using SVM")
plt.xlabel("Math Score")
plt.ylabel("Overall Score")
plt.legend(title="Levels")
plt.grid(True)
plt.xlim(0,100)
plt.ylim(0,100)

plt.show()

input_overall_score = 90
student_level = calculate_grade(input_overall_score)
print(f"For an overall score of {input_overall_score}, the student's level is: ")
if student_level == '1':
  print('A')
elif student_level == '2':
   print('B')
else:
    print('C')

