# -*- coding: utf-8 -*-
"""tsne&autoencoders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phM_Ff5Wk0Dh5xlJh2ETbBnB_EBybGBD
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
from sklearn.manifold import TSNE

# Set random seed for reproducibility
np.random.seed(42)
sns.set_theme(style="white")

# Load MNIST data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize pixel values to [0, 1] and flatten 28x28 images to 784 vectors
X_train_flat = X_train.astype('float32') / 255.0
X_train_flat = X_train_flat.reshape((len(X_train_flat), np.prod(X_train_flat.shape[1:])))

X_test_flat = X_test.astype('float32') / 255.0
X_test_flat = X_test_flat.reshape((len(X_test_flat), np.prod(X_test_flat.shape[1:])))

# Take a subset of 3,000 samples for efficient t-SNE computation and clear plotting
sub_size = 3000
indices = np.random.choice(len(X_test_flat), sub_size, replace=False)
X_subset = X_test_flat[indices]
y_subset = y_test[indices]

print(f"Full Training shape: {X_train_flat.shape}")
print(f"Visualization Subset shape: {X_subset.shape}")

# Define the size of our encoded representations
input_dim = 784
encoding_dim = 2  # Directly compressing to 2D for visualization

# Build the Autoencoder Model
autoencoder = Sequential([
    # Encoder
    Dense(128, activation='relu', input_shape=(input_dim,)),
    Dense(64, activation='relu'),
    Dense(encoding_dim, activation='linear', name='bottleneck'), # 2D Latent Space

    # Decoder
    Dense(64, activation='relu'),
    Dense(128, activation='relu'),
    Dense(input_dim, activation='sigmoid')
])

autoencoder.compile(optimizer='adam', loss='binary_crossentropy')
autoencoder.summary()

# Train the Autoencoder
print("\n--- Training Autoencoder ---")
history = autoencoder.fit(
    X_train_flat, X_train_flat,
    epochs=20,
    batch_size=256,
    shuffle=True,
    validation_data=(X_test_flat, X_test_flat),
    verbose=1
)

encoder_model = Model(inputs=autoencoder.layers[0].input, outputs=autoencoder.get_layer('bottleneck').output)
ae_embeddings = encoder_model.predict(X_subset)

# 2. Compute t-SNE 2D embeddings directly from the raw pixels
print("\n--- Running t-SNE (this might take a few seconds) ---")
tsne = TSNE(n_components=2, perplexity=30, n_iter=1000, random_state=42)
tsne_embeddings = tsne.fit_transform(X_subset)

print("Dimension reduction complete!")

fig, axes = plt.subplots(1, 2, figsize=(18, 8))

# Plot Autoencoder Latent Space
scatter1 = axes[0].scatter(ae_embeddings[:, 0], ae_embeddings[:, 1], c=y_subset, cmap='tab10', alpha=0.6, s=15)
axes[0].set_title('2D Autoencoder Bottleneck Representation', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Latent Feature 1')
axes[0].set_ylabel('Latent Feature 2')
fig.colorbar(scatter1, ax=axes[0], ticks=range(10), label='Digit Class')

# Plot t-SNE Representation
scatter2 = axes[1].scatter(tsne_embeddings[:, 0], tsne_embeddings[:, 1], c=y_subset, cmap='tab10', alpha=0.6, s=15)
axes[1].set_title('2D t-SNE Projection (from Raw Pixels)', fontsize=14, fontweight='bold')
axes[1].set_xlabel('t-SNE Dimension 1')
axes[1].set_ylabel('t-SNE Dimension 2')
fig.colorbar(scatter2, ax=axes[1], ticks=range(10), label='Digit Class')

plt.tight_layout()
plt.show()

