# -*- coding: utf-8 -*-
"""XGBoost 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xltAmviiIMQ8yz_G0WJhG6EUbi5C0lrn
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/job_salary_prediction_dataset.csv')

df.head()

df.isnull().sum()

x = df.drop(['salary'], axis=1)
y = df['salary']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

x = pd.get_dummies(x,drop_first=True)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

model.score(x_train, y_train)

from xgboost import XGBRegressor

model = XGBRegressor()
model.fit(x_train, y_train)

model.score(x_train, y_train)

